name: JavaScript CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # You can add more Node.js versions if needed

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Check for lint script
      id: check_lint
      run: |
        if npm run | grep -q "lint"; then
          echo "has_lint=true" >> $GITHUB_OUTPUT
        else
          echo "has_lint=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run lint
      if: steps.check_lint.outputs.has_lint == 'true'
      run: npm run lint
    
    - name: Check for test script
      id: check_test
      run: |
        if npm run | grep -q "test"; then
          echo "has_test=true" >> $GITHUB_OUTPUT
        else
          echo "has_test=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Run tests
      if: steps.check_test.outputs.has_test == 'true'
      run: npm test
    
    - name: Check for build script
      id: check_build
      run: |
        if npm run | grep -q "build"; then
          echo "has_build=true" >> $GITHUB_OUTPUT
        else
          echo "has_build=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Build
      if: steps.check_build.outputs.has_build == 'true'
      run: npm run build
    
    - name: Check if coverage directory exists
      id: check_coverage
      run: |
        if [ -d "coverage" ]; then
          echo "has_coverage=true" >> $GITHUB_OUTPUT
        else
          echo "has_coverage=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload test coverage reports
      uses: actions/upload-artifact@v4
      if: steps.check_coverage.outputs.has_coverage == 'true'
      with:
        name: coverage-report
        path: coverage/
        retention-days: 7