name: Express.js CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Remove the cache option since we don't have a lock file
        
    - name: Install dependencies
      run: npm install
    
    - name: List files in directory
      run: ls -la
      
    - name: Display package.json content
      run: cat package.json
      
    - name: Check for test script
      id: check_test
      run: |
        if grep -q "\"test\":" package.json; then
          echo "has_test=true" >> $GITHUB_OUTPUT
        else
          echo "has_test=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Run tests
      if: steps.check_test.outputs.has_test == 'true'
      run: npm test
      
    - name: Verify server starts
      run: |
        # Start the server in the background
        node server.js &
        SERVER_PID=$!
        
        # Wait for server to start (adjust sleep time as needed)
        sleep 5
        
        # Check if server is running
        if ps -p $SERVER_PID > /dev/null; then
          echo "Server started successfully"
          kill $SERVER_PID
          exit 0
        else
          echo "Server failed to start"
          exit 1
        fi